version: 3.7

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true
    
services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname==worker1
    networks:
      - frontend
  
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==worker1    
    
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==worker1
          - node.hostname==worker2

  db:
    image: postgres:9.4
    volumes:
      - votedb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==worker2

  results:
    image: bretfisher/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==worker2
   
volumes:
  votedb:
   
